//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\uvnc bvba\\UltraVNC")]
        public string defaultWayToVNC {
            get {
                return ((string)(this["defaultWayToVNC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adspromote.ru")]
        public string defaultIpRepeaterServer {
            get {
                return ((string)(this["defaultIpRepeaterServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adspromote.ru")]
        public string defaultIpRepeaterUVNC {
            get {
                return ((string)(this["defaultIpRepeaterUVNC"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34001")]
        public int defaultPortRepeaterServer {
            get {
                return ((int)(this["defaultPortRepeaterServer"]));
            }
            set {
                this["defaultPortRepeaterServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vncviewer")]
        public string UvncStartFile {
            get {
                return ((string)(this["UvncStartFile"]));
            }
            set {
                this["UvncStartFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5500")]
        public int defaultPortRepeaterUVNC {
            get {
                return ((int)(this["defaultPortRepeaterUVNC"]));
            }
            set {
                this["defaultPortRepeaterUVNC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("update")]
        public string Updater {
            get {
                return ((string)(this["Updater"]));
            }
            set {
                this["Updater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://adspromote.ru:34002")]
        public string serverUpdater {
            get {
                return ((string)(this["serverUpdater"]));
            }
            set {
                this["serverUpdater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VersionAdmin.ini")]
        public string fileNameWithVersion {
            get {
                return ((string)(this["fileNameWithVersion"]));
            }
            set {
                this["fileNameWithVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ListFilesUpdaterAdmin.ini")]
        public string ListFiles {
            get {
                return ((string)(this["ListFiles"]));
            }
            set {
                this["ListFiles"] = value;
            }
        }
    }
}
